local function _ipairs(t, var)
	var = var + 1
	local value = t[var]
	if value == nil then return end
	return var, value
end
local function iterateFromZero(t) return _ipairs, t, -1 end
local function iterateDefault(t) return _ipairs, t, 0 end

Data = {}
local damageTypes = {
	[0] = "None",
	"Physical",
	"Piercing",
	"Corrosive",
	"Magic",
	"Chaos",
	"Fire",
	"Air",
	"Water",
	"Earth",
	"Poison",
	"Shadow"
}
Data.DamageTypes = setmetatable({},{__index = damageTypes})
function Data.DamageTypes:Get()
	return iterateFromZero(self)
end

Data.DamageTypeEnums = {
	None = 0,
	Physical = 1,
	Piercing = 2,
	Corrosive = 3,
	Magic = 4,
	Chaos = 5,
	Fire = 6,
	Air = 7,
	Water = 8,
	Earth = 9,
	Poison = 10,
	Shadow = 11
}
local slots = {
	[0] = "Weapon",
	"Shield",
	"Helmet",
	"Breast",
	"Gloves",
	"Leggings",
	"Boots",
	"Belt",
	"Amulet",
	"Ring",
	"Ring2",
	"Wings",
	"Horns",
	"Overhead"
}
Data.EquipmentSlots = setmetatable({},{__index = slots})
function Data.EquipmentSlots:Get()
	return iterateFromZero(self)
end

local visibleEquipmentSlots = {
	[0] = "Weapon",
	"Shield",
	"Helmet",
	"Breast",
	"Gloves",
	"Leggings",
	"Boots",
	"Belt",
	"Amulet",
	"Ring",
	"Ring2"
}
Data.VisibleEquipmentSlots = setmetatable({},{__index = visibleEquipmentSlots})
function Data.VisibleEquipmentSlots:Get()
	return iterateFromZero(self)
end

--- Enums for every ability in the game.
---@type table<string,integer>
Data.AbilityEnum = {
	WarriorLore = 0,
	RangerLore = 1,
	RogueLore = 2,
	SingleHanded = 3,
	TwoHanded = 4,
	PainReflection = 5,
	Ranged = 6,
	Shield = 7,
	Reflexes = 8,
	PhysicalArmorMastery = 9,
	MagicArmorMastery = 10,
	VitalityMastery = 11,
	Sourcery = 12,
	FireSpecialist = 13,
	WaterSpecialist = 14,
	AirSpecialist = 15,
	EarthSpecialist = 16,
	Necromancy = 17,
	Summoning = 18,
	Polymorph = 19,
	Telekinesis = 20,
	Repair = 21,
	Sneaking = 22,
	Pickpocket = 23,
	Thievery = 24,
	Loremaster = 25,
	Crafting = 26,
	Barter = 27,
	Charm = 28,
	Intimidate = 29,
	Reason = 30,
	Persuasion = 31,
	Leadership = 32,
	Luck = 33,
	DualWielding = 34,
	Wand = 35,
	Perseverance = 36,
	Runecrafting = 37,
	Brewmaster = 38,
	Sulfurology = 39,
	Sentinel = 40,
}
local abilityValues = {}
for name,i in pairs(Data.AbilityEnum) do
	abilityValues[i] = name
end

---@type table<integer,string>
Data.Ability = setmetatable({},{__index = abilityValues})
function Data.Ability:Get()
	return iterateFromZero(self)
end

local attributes = {
	[0] = "Strength",
	"Finesse",
	"Intelligence",
	"Constitution",
	"Memory",
	"Wits"
}
Data.Attribute = setmetatable({},{__index = attributes})
function Data.Attribute:Get()
	return iterateFromZero(self)
end

local talents = {
	"ItemMovement",
	"ItemCreation",
	"Flanking",
	"AttackOfOpportunity",
	"Backstab",
	"Trade",
	"Lockpick",
	"ChanceToHitRanged",
	"ChanceToHitMelee",
	"Damage",
	"ActionPoints",
	"ActionPoints2",
	"Criticals",
	"IncreasedArmor",
	"Sight",
	"ResistFear",
	"ResistKnockdown",
	"ResistStun",
	"ResistPoison",
	"ResistSilence",
	"ResistDead",
	"Carry",
	"Throwing",
	"Repair",
	"ExpGain",
	"ExtraStatPoints",
	"ExtraSkillPoints",
	"Durability",
	"Awareness",
	"Vitality",
	"FireSpells",
	"WaterSpells",
	"AirSpells",
	"EarthSpells",
	"Charm",
	"Intimidate",
	"Reason",
	"Luck",
	"Initiative",
	"InventoryAccess",
	"AvoidDetection",
	"AnimalEmpathy",
	"Escapist",
	"StandYourGround",
	"SurpriseAttack",
	"LightStep",
	"ResurrectToFullHealth",
	"Scientist",
	"Raistlin",
	"MrKnowItAll",
	"WhatARush",
	"FaroutDude",
	"Leech",
	"ElementalAffinity",
	"FiveStarRestaurant",
	"Bully",
	"ElementalRanger",
	"LightningRod",
	"Politician",
	"WeatherProof",
	"LoneWolf",
	"Zombie",
	"Demon",
	"IceKing",
	"Courageous",
	"GoldenMage",
	"WalkItOff",
	"FolkDancer",
	"SpillNoBlood",
	"Stench",
	"Kickstarter",
	"WarriorLoreNaturalArmor",
	"WarriorLoreNaturalHealth",
	"WarriorLoreNaturalResistance",
	"RangerLoreArrowRecover",
	"RangerLoreEvasionBonus",
	"RangerLoreRangedAPBonus",
	"RogueLoreDaggerAPBonus",
	"RogueLoreDaggerBackStab",
	"RogueLoreMovementBonus",
	"RogueLoreHoldResistance",
	"NoAttackOfOpportunity",
	"WarriorLoreGrenadeRange",
	"RogueLoreGrenadePrecision",
	"WandCharge",
	"DualWieldingDodging",
	"Human_Inventive",
	"Human_Civil",
	"Elf_Lore",
	"Elf_CorpseEating",
	"Dwarf_Sturdy",
	"Dwarf_Sneaking",
	"Lizard_Resistance",
	"Lizard_Persuasion",
	"Perfectionist",
	"Executioner",
	"ViolentMagic",
	"QuickStep",
	"Quest_SpidersKiss_Str",
	"Quest_SpidersKiss_Int",
	"Quest_SpidersKiss_Per",
	"Quest_SpidersKiss_Null",
	"Memory",
	"Quest_TradeSecrets",
	"Quest_GhostTree",
	"BeastMaster",
	"LivingArmor",
	"Torturer",
	"Ambidextrous",
	"Unstable",
	"ResurrectExtraHealth",
	"NaturalConductor",
	"Quest_Rooted",
	"PainDrinker",
	"DeathfogResistant",
	"Sourcerer",
	"Rager",
	"Elementalist",
	"Sadist",
	"Haymaker",
	"Gladiator",
	"Indomitable",
	"WildMag",
	"Jitterbug",
	"Soulcatcher",
	"MasterThief",
	"GreedyVessel",
	"MagicCycles",
}
Data.Talents = setmetatable({},{__index = talents})
function Data.Talents:Get()
	return iterateDefault(self)
end

---@type table<string,integer>
Data.TalentEnum = {}
for i,talent in Data.Talents:Get() do
	Data.TalentEnum[talent] = i
end

Data.ItemRarities = {
	"Common",
	"Unique",
	"Uncommon",
	"Rare",
	"Epic",
	"Legendary",
	"Divine",
}

Data.RarityEnum = {
	Common = 0,
	Unique = 1,
	Uncommon = 2,
	Rare = 3,
	Epic = 4,
	Legendary = 5,
	Divine = 6,
}

Data.UI = {
	TOOLTIP_ENUM = {
		"ItemName",
		"ItemWeight",
		"ItemGoldValue",
		"ItemLevel",
		"ItemDescription",
		"ItemRarity",
		"ItemUseAPCost",
		"ItemAttackAPCost",
		"StatBoost",
		"ResistanceBoost",
		"AbilityBoost",
		"OtherStatBoost",
		"VitalityBoost",
		"ChanceToHitBoost",
		"DamageBoost",
		"APCostBoost",
		"APMaximumBoost",
		"APStartBoost",
		"APRecoveryBoost",
		"CritChanceBoost",
		"ArmorBoost",
		"ConsumableDuration",
		"ConsumablePermanentDuration",
		"ConsumableEffect",
		"ConsumableDamage",
		"ExtraProperties",
		"Flags",
		"ItemRequirement",
		"WeaponDamage",
		"WeaponDamagePenalty",
		"WeaponCritMultiplier",
		"WeaponCritChance",
		"WeaponRange",
		"Durability",
		"CanBackstab",
		"AccuracyBoost",
		"DodgeBoost",
		"EquipmentUnlockedSkill",
		"WandSkill",
		"WandCharges",
		"ArmorValue",
		"ArmorSlotType",
		"Blocking",
		"NeedsIdentifyLevel",
		"IsQuestItem",
		"PriceToIdentify",
		"PriceToRepair",
		"PickpocketInfo",
		"Engraving",
		"ContainerIsLocked",
		"SkillName",
		"SkillIcon",
		"SkillSchool",
		"SkillTier",
		"SkillRequiredEquipment",
		"SkillAPCost",
		"SkillCooldown",
		"SkillDescription",
		"SkillProperties",
		"SkillDamage",
		"SkillRange",
		"SkillExplodeRadius",
		"SkillCanPierce",
		"SkillCanFork",
		"SkillStrikeCount",
		"SkillProjectileCount",
		"SkillCleansesStatus",
		"SkillMultiStrikeAttacks",
		"SkillWallDistance",
		"SkillPathSurface",
		"SkillPathDistance",
		"SkillHealAmount",
		"SkillDuration",
		"ConsumableEffectUknown",
		"Reflection",
		"SkillAlreadyLearned",
		"SkillOnCooldown",
		"SkillAlreadyUsed",
		"AbilityTitle",
		"AbilityDescription",
		"TalentTitle",
		"TalentDescription",
		"SkillMPCost",
		"MagicArmorValue",
		"WarningText",
		"RuneSlot",
		"RuneEffect",
		"Equipped",
		"ShowSkillIcon",
		"SkillbookSkill",
		"Tags",
		"EmptyRuneSlot",
		"StatName",
		"StatsDescription",
		"StatsDescriptionBoost",
		"StatSTRWeight",
		"StatMEMSlot",
		"StatsPointValue",
		"StatsTalentsBoost",
		"StatsTalentsMalus",
		"StatsBaseValue",
		"StatsPercentageBoost",
		"StatsPercentageMalus",
		"StatsPercentageTotal",
		"StatsGearBoostNormal",
		"StatsATKAPCost",
		"StatsCriticalInfos",
		"StatsAPTitle",
		"StatsAPDesc",
		"StatsAPBase",
		"StatsAPBonus",
		"StatsAPMalus",
		"StatsTotalDamage",
		"TagDescription",
		"StatusImmunity",
		"StatusBonus",
		"StatusMalus",
		"StatusDescription",
		"Title",
		"SurfaceDescription",
		"Duration",
		"Fire",
		"Water",
		"Earth",
		"Air",
		"Poison",
		"Physical",
		"Sulfur",
		"Heal",
		"Splitter",
	},
	---Used to build tooltips.
	---@class TOOLTIP_TYPE
	TOOLTIP_TYPE = {
		ItemName = 1,
		ItemWeight = 2,
		ItemGoldValue = 3,
		ItemLevel = 4,
		ItemDescription = 5,
		ItemRarity = 6,
		ItemUseAPCost = 7,
		ItemAttackAPCost = 8,
		StatBoost = 9,
		ResistanceBoost = 10,
		AbilityBoost = 11,
		OtherStatBoost = 12,
		VitalityBoost = 13,
		ChanceToHitBoost = 14,
		DamageBoost = 15,
		APCostBoost = 16,
		APMaximumBoost = 17,
		APStartBoost = 18,
		APRecoveryBoost = 19,
		CritChanceBoost = 20,
		ArmorBoost = 21,
		ConsumableDuration = 22,
		ConsumablePermanentDuration = 23,
		ConsumableEffect = 24,
		ConsumableDamage = 25,
		ExtraProperties = 26,
		Flags = 27,
		ItemRequirement = 28,
		WeaponDamage = 29,
		WeaponDamagePenalty = 30,
		WeaponCritMultiplier = 31,
		WeaponCritChance = 32,
		WeaponRange = 33,
		Durability = 34,
		CanBackstab = 35,
		AccuracyBoost = 36,
		DodgeBoost = 37,
		EquipmentUnlockedSkill = 38,
		WandSkill = 39,
		WandCharges = 40,
		ArmorValue = 41,
		ArmorSlotType = 42,
		Blocking = 43,
		NeedsIdentifyLevel = 44,
		IsQuestItem = 45,
		PriceToIdentify = 46,
		PriceToRepair = 47,
		PickpocketInfo = 48,
		Engraving = 49,
		ContainerIsLocked = 50,
		SkillName = 51,
		SkillIcon = 52,
		SkillSchool = 53,
		SkillTier = 54,
		SkillRequiredEquipment = 55,
		SkillAPCost = 56,
		SkillCooldown = 57,
		SkillDescription = 58,
		SkillProperties = 59,
		SkillDamage = 60,
		SkillRange = 61,
		SkillExplodeRadius = 62,
		SkillCanPierce = 63,
		SkillCanFork = 64,
		SkillStrikeCount = 65,
		SkillProjectileCount = 66,
		SkillCleansesStatus = 67,
		SkillMultiStrikeAttacks = 68,
		SkillWallDistance = 69,
		SkillPathSurface = 70,
		SkillPathDistance = 71,
		SkillHealAmount = 72,
		SkillDuration = 73,
		ConsumableEffectUknown = 74,
		Reflection = 75,
		SkillAlreadyLearned = 76,
		SkillOnCooldown = 77,
		SkillAlreadyUsed = 78,
		AbilityTitle = 79,
		AbilityDescription = 80,
		TalentTitle = 81,
		TalentDescription = 82,
		SkillMPCost = 83,
		MagicArmorValue = 84,
		WarningText = 85,
		RuneSlot = 86,
		RuneEffect = 87,
		Equipped = 88,
		ShowSkillIcon = 89,
		SkillbookSkill = 90,
		Tags = 91,
		EmptyRuneSlot = 92,
		StatName = 93,
		StatsDescription = 94,
		StatsDescriptionBoost = 95,
		StatSTRWeight = 96,
		StatMEMSlot = 97,
		StatsPointValue = 98,
		StatsTalentsBoost = 99,
		StatsTalentsMalus = 100,
		StatsBaseValue = 101,
		StatsPercentageBoost = 102,
		StatsPercentageMalus = 103,
		StatsPercentageTotal = 104,
		StatsGearBoostNormal = 105,
		StatsATKAPCost = 106,
		StatsCriticalInfos = 107,
		StatsAPTitle = 108,
		StatsAPDesc = 109,
		StatsAPBase = 110,
		StatsAPBonus = 111,
		StatsAPMalus = 112,
		StatsTotalDamage = 113,
		TagDescription = 114,
		StatusImmunity = 115,
		StatusBonus = 116,
		StatusMalus = 117,
		StatusDescription = 118,
		Title = 119,
		SurfaceDescription = 120,
		Duration = 121,
		Fire = 122,
		Water = 123,
		Earth = 124,
		Air = 125,
		Poison = 126,
		Physical = 127,
		Sulfur = 128,
		Heal = 129,
		Splitter = 130,
	}
}

ID = {
	MESSAGE = {
		ATTRIBUTE_CHANGED = "ATTRIBUTE_CHANGED",
		ABILITY_CHANGED = "ABILITY_CHANGED",
		STORE_PARTY_VALUES = "STORE_PARTY_VALUES"
	},
	HOTBAR = {
		CharacterSheet = 1
	}
}

SKILL_STATE = {
	PREPARE = "PREPARE",
	USED = "USED",
	CAST = "CAST",
	HIT = "HIT",
}