Data = {
	DamageTypes = {
		[0] = "None",
		"Physical",
		"Piercing",
		"Corrosive",
		"Magic",
		"Chaos",
		"Fire",
		"Air",
		"Water",
		"Earth",
		"Poison",
		"Shadow"
	},
	DamageTypeEnums = {
		None = 0,
		Physical = 1,
		Piercing = 2,
		Corrosive = 3,
		Magic = 4,
		Chaos = 5,
		Fire = 6,
		Air = 7,
		Water = 8,
		Earth = 9,
		Poison = 10,
		Shadow = 11
	},
	EquipmentSlots = {
		[0] = "Weapon",
		"Shield",
		"Helmet",
		"Breast",
		"Gloves",
		"Leggings",
		"Boots",
		"Belt",
		"Amulet",
		"Ring",
		"Ring2",
		"Wings",
		"Horns",
		"Overhead"
	},
	VisibleEquipmentSlots = {
		[0] = "Weapon",
		"Shield",
		"Helmet",
		"Breast",
		"Gloves",
		"Leggings",
		"Boots",
		"Belt",
		"Amulet",
		"Ring",
		"Ring2"
	},
	--- Enums for every ability in the game.
	---@type table<string,integer>
	AbilityEnum = {
		WarriorLore = 0,
		RangerLore = 1,
		RogueLore = 2,
		SingleHanded = 3,
		TwoHanded = 4,
		PainReflection = 5,
		Ranged = 6,
		Shield = 7,
		Reflexes = 8,
		PhysicalArmorMastery = 9,
		MagicArmorMastery = 10,
		VitalityMastery = 11,
		Sourcery = 12,
		FireSpecialist = 13,
		WaterSpecialist = 14,
		AirSpecialist = 15,
		EarthSpecialist = 16,
		Necromancy = 17,
		Summoning = 18,
		Polymorph = 19,
		Telekinesis = 20,
		Repair = 21,
		Sneaking = 22,
		Pickpocket = 23,
		Thievery = 24,
		Loremaster = 25,
		Crafting = 26,
		Barter = 27,
		Charm = 28,
		Intimidate = 29,
		Reason = 30,
		Persuasion = 31,
		Leadership = 32,
		Luck = 33,
		DualWielding = 34,
		Wand = 35,
		Perseverance = 36,
		Runecrafting = 37,
		Brewmaster = 38,
		Sulfurology = 39,
		Sentinel = 40,
	},
	---@type table<integer,string>
	Ability = {},
	Attribute = {
		[0] = "Strength",
		"Finesse",
		"Intelligence",
		"Constitution",
		"Memory",
		"Wits"
	},
	UI = {
		---Used to build tooltips.
		---@class TOOLTIP_TYPE
		TOOLTIP_TYPE = {
			ItemName = 0,
			ItemWeight = 1,
			ItemGoldValue = 2,
			ItemLevel = 3,
			ItemDescription = 4,
			ItemRarity = 5,
			ItemUseAPCost = 6,
			ItemAttackAPCost = 7,
			StatBoost = 8,
			ResistanceBoost = 9,
			AbilityBoost = 10,
			OtherStatBoost = 11,
			VitalityBoost = 12,
			ChanceToHitBoost = 13,
			DamageBoost = 14,
			APCostBoost = 15,
			APMaximumBoost = 16,
			APStartBoost = 17,
			APRecoveryBoost = 18,
			CritChanceBoost = 19,
			ArmorBoost = 20,
			ConsumableDuration = 21,
			ConsumablePermanentDuration = 22,
			ConsumableEffect = 23,
			ConsumableDamage = 24,
			ExtraProperties = 25,
			Flags = 26,
			ItemRequirement = 27,
			WeaponDamage = 28,
			WeaponDamagePenalty = 29,
			WeaponCritMultiplier = 30,
			WeaponCritChance = 31,
			WeaponRange = 32,
			Durability = 33,
			CanBackstab = 34,
			AccuracyBoost = 35,
			DodgeBoost = 36,
			EquipmentUnlockedSkill = 37,
			WandSkill = 38,
			WandCharges = 39,
			ArmorValue = 40,
			ArmorSlotType = 41,
			Blocking = 42,
			NeedsIdentifyLevel = 43,
			IsQuestItem = 44,
			PriceToIdentify = 45,
			PriceToRepair = 46,
			PickpocketInfo = 47,
			Engraving = 48,
			ContainerIsLocked = 49,
			SkillName = 50,
			SkillIcon = 51,
			SkillSchool = 52,
			SkillTier = 53,
			SkillRequiredEquipment = 54,
			SkillAPCost = 55,
			SkillCooldown = 56,
			SkillDescription = 57,
			SkillProperties = 58,
			SkillDamage = 59,
			SkillRange = 60,
			SkillExplodeRadius = 61,
			SkillCanPierce = 62,
			SkillCanFork = 63,
			SkillStrikeCount = 64,
			SkillProjectileCount = 65,
			SkillCleansesStatus = 66,
			SkillMultiStrikeAttacks = 67,
			SkillWallDistance = 68,
			SkillPathSurface = 69,
			SkillPathDistance = 70,
			SkillHealAmount = 71,
			SkillDuration = 72,
			ConsumableEffectUknown = 73,
			Reflection = 74,
			SkillAlreadyLearned = 75,
			SkillOnCooldown = 76,
			SkillAlreadyUsed = 77,
			AbilityTitle = 78,
			AbilityDescription = 79,
			TalentTitle = 80,
			TalentDescription = 81,
			SkillMPCost = 82,
			MagicArmorValue = 83,
			WarningText = 84,
			RuneSlot = 85,
			RuneEffect = 86,
			Equipped = 87,
			ShowSkillIcon = 88,
			SkillbookSkill = 89,
			Tags = 90,
			EmptyRuneSlot = 91,
			StatName = 92,
			StatsDescription = 93,
			StatsDescriptionBoost = 94,
			StatSTRWeight = 95,
			StatMEMSlot = 96,
			StatsPointValue = 97,
			StatsTalentsBoost = 98,
			StatsTalentsMalus = 99,
			StatsBaseValue = 100,
			StatsPercentageBoost = 101,
			StatsPercentageMalus = 102,
			StatsPercentageTotal = 103,
			StatsGearBoostNormal = 104,
			StatsATKAPCost = 105,
			StatsCriticalInfos = 106,
			StatsAPTitle = 107,
			StatsAPDesc = 108,
			StatsAPBase = 109,
			StatsAPBonus = 110,
			StatsAPMalus = 111,
			StatsTotalDamage = 112,
			TagDescription = 113,
			StatusImmunity = 114,
			StatusBonus = 115,
			StatusMalus = 116,
			StatusDescription = 117,
			Title = 118,
			SurfaceDescription = 119,
			Duration = 120,
			Fire = 121,
			Water = 122,
			Earth = 123,
			Air = 124,
			Poison = 125,
			Physical = 126,
			Sulfur = 127,
			Heal = 128,
			Splitter = 129,
		}
	},
}

for name,i in pairs(Data.AbilityEnum) do
	Data.Ability[i] = name
end

ID = {
	MESSAGE = {
		ATTRIBUTE_CHANGED = "ATTRIBUTE_CHANGED",
		ABILITY_CHANGED = "ABILITY_CHANGED",
		STORE_PARTY_VALUES = "STORE_PARTY_VALUES"
	},
	HOTBAR = {
		CharacterSheet = 1
	}
}

SKILL_STATE = {
	PREPARE = "PREPARE",
	USED = "USED",
	CAST = "CAST",
	HIT = "HIT",
}