if DebugHelpers == nil then
	DebugHelpers = {}
end

local EsvItemProps = {
	Activated = "boolean",
	Amount = "integer",
	Armor = "integer",
	CanBeMoved = "boolean",
	CanBePickedUp = "boolean",
	CanConsume = "boolean",
	CanShootThrough = "boolean",
	CanUse = "boolean",
	CurrentLevel = "string",
	CustomBookContent = "string",
	CustomDescription = "string",
	CustomDisplayName = "string",
	Destroy = "boolean",
	Destroyed = "boolean",
	DisplayName = "string",
	DoorFlag = "boolean",
	Floating = "boolean",
	ForceSync = "boolean",
	ForceSynch = "boolean",
	FreezeGravity = "boolean",
	Frozen = "boolean",
	Global = "boolean",
	GMFolding = "boolean",
	GoldValueOverwrite = "integer",
	Handle = "ObjectHandle",
	InteractionDisabled = "boolean",
	InUseByCharacterHandle = "ObjectHandle",
	InventoryHandle = "ObjectHandle",
	IsDoor = "boolean",
	IsKey = "boolean",
	IsLadder = "boolean",
	IsSurfaceBlocker = "boolean",
	IsSurfaceCloudBlocker = "boolean",
	ItemType = "string",
	Key = "string",
	LevelOverride = "integer",
	LoadedTemplate = "boolean",
	LockLevel = "integer",
	NoCover = "boolean",
	MyGuid = "string",
	OffStage = "boolean",
	OwnerHandle = "ObjectHandle",
	ParentInventoryHandle = "ObjectHandle",
	PinnedContainer = "boolean",
	PositionChanged = "boolean",
	RootTemplate = "ItemTemplate",
	Scale = "number",
	Slot = "integer",
	SourceContainer = "boolean",
	Stats = "StatItem",
	StatsId = "string",
	Sticky = "boolean",
	StoryItem = "boolean",
	Summon = "boolean",
	TeleportOnUse = "boolean",
	Totem = "boolean",
	TreasureGenerated = "boolean",
	TreasureLevel = "integer",
	UnEquipLocked = "boolean",
	UnsoldGenerated = "boolean",
	UseRemotely = "boolean",
	Vitality = "integer",
	WalkOn = "boolean",
	WalkThrough = "boolean",
	WeightValueOverwrite = "integer",
	WorldPos = "number[]",
}

local CDivinityStats_Item = {
	Level = "integer",
	Name = "string",
	InstanceId = "integer",
	ItemType = "string",
	ItemSlot = "string",
	WeaponType = "string",
	AnimType = "integer",
	WeaponRange = "integer",
	IsIdentified = "integer",
	IsTwoHanded = "boolean",
	ShouldSyncStats = "boolean",
	HasModifiedSkills = "boolean",
	Skills = "string",
	DamageTypeOverwrite = "string",
	Durability = "integer",
	DurabilityCounter = "integer",
	ItemTypeReal = "string",
	MaxCharges = "integer",
	Charges = "integer",
	DynamicStats = "StatItemDynamic",
	Using = "string",
	Damage = "integer",
	Act = "string",
	Handedness = "string",
	DamageBoost = "integer",
	DamageFromBase = "integer",
	CriticalDamage = "integer",
	CriticalChance = "integer",
	Movement = "integer",
	Initiative = "integer",
	Requirements = "StatRequirement",
	Slot = "string",
	DurabilityDegradeSpeed = "string",
	Value = "integer",
	ModifierType = "string",
	Projectile = "string",
	StrengthBoost = "string",
	FinesseBoost = "string",
	IntelligenceBoost = "string",
	ConstitutionBoost = "string",
	MemoryBoost = "string",
	WitsBoost = "string",
	SingleHanded = "integer",
	TwoHanded = "integer",
	Ranged = "integer",
	DualWielding = "integer",
	RogueLore = "integer",
	WarriorLore = "integer",
	RangerLore = "integer",
	FireSpecialist = "integer",
	WaterSpecialist = "integer",
	AirSpecialist = "integer",
	EarthSpecialist = "integer",
	Sourcery = "integer",
	Necromancy = "integer",
	Polymorph = "integer",
	Summoning = "integer",
	Leadership = "integer",
	PainReflection = "integer",
	Perseverance = "integer",
	Telekinesis = "integer",
	Sneaking = "integer",
	Thievery = "integer",
	Loremaster = "integer",
	Repair = "integer",
	Barter = "integer",
	Persuasion = "integer",
	Luck = "integer",
	Fire = "integer",
	Earth = "integer",
	Water = "integer",
	Air = "integer",
	Poison = "integer",
	Physical = "integer",
	Piercing = "integer",
	SightBoost = "string",
	HearingBoost = "string",
	VitalityBoost = "integer",
	MagicPointsBoost = "string",
	ChanceToHitBoost = "integer",
	APMaximum = "integer",
	APStart = "integer",
	APRecovery = "integer",
	AccuracyBoost = "integer",
	DodgeBoost = "integer",
	Weight = "integer",
	AttackAPCost = "integer",
	ComboCategory = "string",
	Flags = "string",
	Boosts = "string",
	InventoryTab = "string",
	Reflection = "string",
	ItemGroup = "string",
	ObjectCategory = "string",
	MinAmount = "integer",
	MaxAmount = "integer",
	Priority = "integer",
	Unique = "integer",
	MinLevel = "integer",
	MaxLevel = "integer",
	ItemColor = "string",
	MaxSummons = "integer",
	RuneSlots = "integer",
	RuneSlots_V1 = "integer",
	NeedsIdentification = "string",
	LifeSteal = "integer",
	CleavePercentage = "integer",
	CleaveAngle = "integer",
	Talents = "string",
	IgnoreVisionBlock = "string",
	Tags = "string",
	ArmorBoost = "integer",
	MagicArmorBoost = "integer",
	Blocking = "integer",
	ExtraProperties = "StatProperty",
}

local CDivinityStats_Equipment_Attributes = {
	AccuracyBoost = "integer",
	AirResistance = "integer",
	APRecovery = "integer",
	ArmorBoost = "integer",
	ArmorValue = "integer",
	AttackAPCost = "integer",
	Blocking = "integer",
	Bodybuilding = "integer",
	BoostName = "string",
	ChanceToHitBoost = "integer",
	CleaveAngle = "integer",
	CleavePercentage = "integer",
	ConstitutionBoost = "integer",
	CorrosiveResistance = "integer",
	CriticalChance = "integer",
	CriticalDamage = "integer",
	--CustomResistance = "integer",
	DamageBoost = "integer",
	--DamageFromBase = "integer",
	--DamageType = "integer",
	DodgeBoost = "integer",
	Durability = "integer",
	DurabilityDegradeSpeed = "integer",
	EarthResistance = "integer",
	FinesseBoost = "integer",
	FireResistance = "integer",
	HearingBoost = "integer",
	Initiative = "integer",
	IntelligenceBoost = "integer",
	ItemColor = "string",
	LifeSteal = "integer",
	MagicArmorBoost = "integer",
	MagicArmorValue = "integer",
	MagicResistance = "integer",
	MaxAP = "integer",
	-- MinDamage = "integer",
	-- MaxDamage = "integer",
	MaxSummons = "integer",
	MemoryBoost = "integer",
	ModifierType = "integer",
	Movement = "integer",
	MovementSpeedBoost = "integer",
	ObjectInstanceName = "string",
	PhysicalResistance = "integer",
	PiercingResistance = "integer",
	PoisonResistance = "integer",
	RuneSlots = "integer",
	RuneSlots_V1 = "integer",
	ShadowResistance = "integer",
	SightBoost = "integer",
	Skills = "string",
	SourcePointsBoost = "integer",
	StartAP = "integer",
	StatsType = "string",
	StrengthBoost = "integer",
	Value = "integer",
	VitalityBoost = "integer",
	WaterResistance = "integer",
	WeaponRange = "integer",
	Weight = "integer",
	Willpower = "integer",
	WitsBoost = "integer",
}

local CDivinityStats_Weapon_Attributes = {
	AccuracyBoost = "integer",
	APRecovery = "integer",
	AttackAPCost = "integer",
	Bodybuilding = "integer",
	BoostName = "string",
	ChanceToHitBoost = "integer",
	CleaveAngle = "integer",
	CleavePercentage = "integer",
	ConstitutionBoost = "integer",
	CriticalChance = "integer",
	CriticalDamage = "integer",
	DamageBoost = "integer",
	DamageFromBase = "integer",
	DamageType = "integer",
	DodgeBoost = "integer",
	Durability = "integer",
	DurabilityDegradeSpeed = "integer",
	FinesseBoost = "integer",
	HearingBoost = "integer",
	Initiative = "integer",
	IntelligenceBoost = "integer",
	ItemColor = "string",
	LifeSteal = "integer",
	MaxAP = "integer",
	MaxDamage = "integer",
	MaxSummons = "integer",
	MemoryBoost = "integer",
	MinDamage = "integer",
	ModifierType = "integer",
	Movement = "integer",
	MovementSpeedBoost = "integer",
	ObjectInstanceName = "string",
	RuneSlots = "integer",
	RuneSlots_V1 = "integer",
	SightBoost = "integer",
	Skills = "string",
	SourcePointsBoost = "integer",
	StartAP = "integer",
	StatsType = "string",
	StrengthBoost = "integer",
	Value = "integer",
	VitalityBoost = "integer",
	WeaponRange = "integer",
	Weight = "integer",
	Willpower = "integer",
	WitsBoost = "integer",
}

local EsvCharacterProps = {
	RootTemplate = "CharacterTemplate",
	PlayerCustomData = "PlayerCustomData",
	Stats = "StatCharacter",
	DisplayName = "string",
	Handle = "ObjectHandle",
	NetID = "integer",
	MyGuid = "string",
	WorldPos = "number",
	CurrentLevel = "string",
	Scale = "number",
	AnimationOverride = "string",
	WalkSpeedOverride = "number",
	RunSpeedOverride = "number",
	NeedsUpdateCount = "integer",
	ScriptForceUpdateCount = "integer",
	ForceSynchCount = "integer",
	InventoryHandle = "ObjectHandle",
	SkillBeingPrepared = "string",
	LifeTime = "number",
	TurnTimer = "number",
	TriggerTrapsTimer = "number",
	UserID = "integer",
	ReservedUserID = "integer",
	OwnerHandle = "ObjectHandle",
	FollowCharacterHandle = "ObjectHandle",
	SpiritCharacterHandle = "ObjectHandle",
	CorpseCharacterHandle = "ObjectHandle",
	PartialAP = "number",
	AnimType = "integer",
	DelayDeathCount = "integer",
	AnimationSetOverride = "string",
	OriginalTransformDisplayName = "string",
	PartyHandle = "ObjectHandle",
	CustomTradeTreasure = "string",
	IsAlarmed = "boolean",
	CrimeWarningsEnabled = "boolean",
	CrimeInterrogationEnabled = "boolean",
	MovingCasterHandle = "ObjectHandle",
	Archetype = "string",
	EquipmentColor = "string",
	ProjectileTemplate = "string",
	ReadyCheckBlocked = "boolean",
	CorpseLootable = "boolean",
	CustomBloodSurface = "string",
	PreviousLevel = "string",
	IsPlayer = "boolean",
	Multiplayer = "boolean",
	InParty = "boolean",
	HostControl = "boolean",
	Activated = "boolean",
	OffStage = "boolean",
	Dead = "boolean",
	HasOwner = "boolean",
	InDialog = "boolean",
	Summon = "boolean",
	CannotDie = "boolean",
	CharacterControl = "boolean",
	Loaded = "boolean",
	InArena = "boolean",
	CharacterCreationFinished = "boolean",
	Floating = "boolean",
	SpotSneakers = "boolean",
	Temporary = "boolean",
	WalkThrough = "boolean",
	CoverAmount = "boolean",
	CanShootThrough = "boolean",
	PartyFollower = "boolean",
	Totem = "boolean",
	NoRotate = "boolean",
	Deactivated = "boolean",
	IsHuge = "boolean",
	MadePlayer = "boolean",
	LevelTransitionPending = "boolean",
	RegisteredForAutomatedDialog = "boolean",
	Global = "boolean",
	HasOsirisDialog = "boolean",
	HasDefaultDialog = "boolean",
	TreasureGeneratedForTrader = "boolean",
	Trader = "boolean",
	Resurrected = "boolean",
	IsPet = "boolean",
	IsSpectating = "boolean",
	NoReptuationEffects = "boolean",
	HasWalkSpeedOverride = "boolean",
	HasRunSpeedOverride = "boolean",
	IsGameMaster = "boolean",
	IsPossessed = "boolean",
	ManuallyLeveled = "boolean",
}

local CharacterTemplate = {
	CombatTemplate = "CombatComponentTemplate",
	Icon = "string",
	Stats = "string",
	SkillSet = "string",
	Equipment = "string",
	LightID = "string",
	HitFX = "string",
	DefaultDialog = "string",
	SpeakerGroup = "string",
	GeneratePortrait = "string",
	WalkSpeed = "number",
	RunSpeed = "number",
	ClimbAttachSpeed = "number",
	ClimbLoopSpeed = "number",
	ClimbDetachSpeed = "number",
	CanShootThrough = "boolean",
	WalkThrough = "boolean",
	CanClimbLadders = "boolean",
	IsPlayer = "boolean",
	Floating = "boolean",
	SpotSneakers = "boolean",
	CanOpenDoors = "boolean",
	AvoidTraps = "boolean",
	InfluenceTreasureLevel = "boolean",
	HardcoreOnly = "boolean",
	NotHardcore = "boolean",
	JumpUpLadders = "boolean",
	NoRotate = "boolean",
	IsHuge = "boolean",
	EquipmentClass = "number",
	ExplodedResourceID = "string",
	ExplosionFX = "string",
	VisualSetResourceID = "string",
	VisualSetIndices = "number",
	TrophyID = "string",
	SoundInitEvent = "string",
	SoundAttachBone = "string",
	SoundAttenuation = "number",
	CoverAmount = "number",
	LevelOverride = "number",
	ForceUnsheathSkills = "boolean",
	CanBeTeleported = "boolean",
	ActivationGroupId = "string",
	SoftBodyCollisionTemplate = "string",
	RagdollTemplate = "string",
	DefaultState = "number",
	GhostTemplate = "string",
	IsLootable = "boolean",
	IsEquipmentLootable = "boolean",
	InventoryType = "number",
	IsArenaChampion = "boolean",
	FootstepWeight = "string",
}

local CombatComponentTemplate = {
	Alignment = "string",
	CanFight = "boolean",
	CanJoinCombat = "boolean",
	CombatGroupID = "string",
	IsBoss = "boolean",
	IsInspector = "boolean",
	StartCombatRange = "number",
}

local userDataProps = {
	["esv::Item"] = EsvItemProps,
	["esv::Character"] = EsvCharacterProps,
	["eoc::CharacterTemplate"] = CharacterTemplate,
	["eoc::CombatComponentTemplate"] = CombatComponentTemplate,
	["CDivinityStats_Item"] = CDivinityStats_Item,
	["CDivinityStats_Equipment_Attributes"] = CDivinityStats_Equipment_Attributes,
	["CDivinityStats_Weapon_Attributes"] = CDivinityStats_Weapon_Attributes,
	["CDamageList"] = function(obj) return obj:ToTable() end,
}

local function TryGetValue(obj,k)
	return obj[k]
end

function DebugHelpers.TraceUserData(obj, printNil)
	if obj == nil then
		return "nil"
	end
	local meta = getmetatable(obj)
	local props = userDataProps[meta]
	if props then
		if meta == "CDivinityStats_Equipment_Attributes" and obj.ItemSlot == "Weapon" then
			props = userDataProps.CDivinityStats_Weapon_Attributes
		end
		if type(props) == "function" then
			return Lib.inspect(props(obj))
		else
			local data = {}
			for k,v in pairs(props) do
				local b,value = xpcall(TryGetValue, debug.traceback, obj, k)
				if b and value ~= nil then
					if props == userDataProps.CDivinityStats_Equipment_Attributes and ((type(value) == "number" and value == 0) or (type(value) == "string" and value == "None" or value == "")) then
						-- skip
					else
						data[k] = value
					end
				elseif printNil == true then
					data[k] = string.format("nil (%s)", v)
				end
			end
			return Lib.inspect(data)
		end
	else
		if meta then
			return tostring(meta)
		else
			return tostring(obj)
		end
	end
end