---@diagnostic disable
---@meta

---@class FlashTimerEvent:FlashEvent
---@class FlashMouseEvent:FlashEvent
---@class FlashTimer:FlashObject

---@class FlashListDisplay:FlashMovieClip
---@field content_array FlashArray
---@field scrollHit_mc FlashMovieClip
---@field container_mc FlashMovieClip
---@field containerBG_mc FlashMovieClip
---@field containerContent_mc FlashMovieClip
---@field EL_SPACING number
---@field m_topSpacing number
---@field m_sideSpacing number
---@field m_cyclic boolean
---@field m_customElementWidth number
---@field m_customElementHeight number
---@field m_forceDepthReorder boolean
---@field m_CurrentSelection FlashMovieClip
---@field idInc integer
---@field m_hasScrollRect boolean
---@field OnSelectionChanged function
---@field m_AlphaTweenFunc function
---@field m_PositionTweenFunc function
---@field m_tweeningMcs integer
---@field m_visibleLength number
---@field m_NeedsSorting boolean
---@field m_SortOnFieldName FlashObject
---@field m_SortOnOptions FlashObject
---@field m_positionInvisibleElements boolean
---@field m_height number
---@field m_width number
---@field m_myInterlinie number
---@field setFrameWidth fun(param1:number)
---@field setFrame fun(param1:number, param2:number)
---@field getCurrentMovieClip fun():FlashMovieClip
---@field getElement fun(param1:number):FlashMovieClip
---@field getAt fun(param1:number):FlashMovieClip
---@field getElementByListID fun(param1:number):FlashMovieClip
---@field selectLastElement fun()
---@field isLastElement fun(param1:FlashMovieClip):boolean
---@field isFirstElement fun(param1:FlashMovieClip):boolean
---@field getElementByNumber fun(param1:string, param2:number):FlashMovieClip
---@field getElementByBool fun(param1:string, param2:boolean):FlashMovieClip
---@field selectByOffset fun(param1:number, param2:boolean):boolean
---@field getElementByString fun(param1:string, param2:string):FlashMovieClip
---@field cleanUpElements fun()
---@field positionElements fun()
---@field getElementWidth fun(param1:FlashMovieClip):number
---@field getElementHeight fun(param1:FlashMovieClip):number
---@field getContentHeight fun():number
---@field moveElementsToPosition fun(param1:number, param2:boolean)
---@field moveElementToPosition fun(param1:number, param2:number):boolean
---@field moveElementToBack fun(param1:number)
---@field onRemovedFromStage fun(param1:FlashEvent)
---@field addElement fun(param1:FlashDisplayObject, param2:boolean, param3:boolean)
---@field addElementOnPosition fun(param1:FlashDisplayObject, param2:integer, param3:boolean, param4:boolean)
---@field addElementToFront fun(param1:FlashDisplayObject, param2:boolean)
---@field resetListPos fun()
---@field stopElementTweens fun(param1:number)
---@field fadeOutAndRemoveElement fun(param1:number, param2:number, param3:number, param4:boolean, param5:boolean)
---@field removeElement fun(param1:number, param2:boolean|nil, param3:boolean|nil, param4:number|nil)
---@field removeElementByListId fun(param1:number, param2:boolean):boolean
---@field clearElements fun()
---@field next fun()
---@field previous fun()
---@field getPreviousVisibleElement fun():FlashMovieClip
---@field selectByListID fun(param1:number)
---@field selectMC fun(param1:FlashMovieClip, param2:boolean)
---@field clearSelection fun()
---@field select fun(param1:number, param2:boolean, param3:boolean)
---@field filterShowAll fun()
---@field filterHideAll fun()
---@field filterHideBoolean fun(param1:string, param2:boolean)
---@field filterShowBoolean fun(param1:string, param2:boolean, param3:boolean)
---@field filterBySubString fun(param1:string, param2:string)
---@field filterShowType fun(param1:string, param2:FlashObject, param3:boolean)
---@field filterHideType fun(param1:string, param2:FlashObject)
---@field filterType fun(param1:string, param2:FlashObject)
---@field getFirstElement fun(param1:boolean, param2:boolean):FlashMovieClip
---@field getFirstVisible fun(param1:boolean):FlashMovieClip
---@field getLastElement fun(param1:boolean, param2:boolean):FlashMovieClip
---@field getLastVisible fun(param1:boolean):FlashMovieClip
---@field selectFirstVisible fun(param1:boolean)
---@field sortOn fun(param1:FlashObject, param2:FlashObject, param3:boolean)
---@field redoSort fun()
---@field sortOnce fun(param1:FlashObject, param2:FlashObject, param3:boolean)
---@field cursorLeft fun()
---@field cursorRight fun()
---@field cursorUp fun()
---@field cursorDown fun()
---@field cursorAccept fun()
---@field isOverlappingPosition fun(targetX:number, targetY:number, shapeTest:boolean)

---@class FlashHorizontalList:FlashListDisplay
---@field rightSided boolean
---@field m_MaxWidth integer
---@field m_MaxRowElements integer
---@field m_RowSpacing integer
---@field m_CenterHolders boolean
---@field m_RowHeight number
---@field m_holderArray table
---@field positionElements fun()
---@field moveElementsToPosition fun(param1:number, param2:boolean)
---@field getContainerWidth fun():number

---@class FlashScrollbar:FlashMovieClip

---@class FlashScrollList:FlashListDisplay
---@field m_scrollbar_mc FlashScrollbar
---@field m_bottomAligned boolean
---@field m_allowAutoScroll boolean
---@field m_SBSpacing number
---@field m_mouseWheelWhenOverEnabled boolean
---@field m_mouseWheelEnabled boolean
---@field m_ScrollHeight number
---@field m_allowKeepIntoView boolean
---@field leftAligned boolean
---@field m_TextGlowOffset number
---@field m_dragAutoScroll boolean
---@field m_dragAutoScrollDistance number
---@field m_dragAutoScrollMod number
---@field m_bgTile1_mc FlashMovieClip
---@field m_bgTile2_mc FlashMovieClip
---@field selectMC fun(param1:FlashMovieClip, param2:boolean)
---@field clearElements fun()
---@field resetScroll fun()
---@field selectByOffset fun(param1:number, param2:boolean):boolean
---@field checkScrollBar fun()
---@field setFrameWidth fun(param1:number)
---@field setFrame fun(param1:number, param2:number)
---@field setFrameHeight fun(param1:number)
---@field positionElements fun()

---@class CombatLogFlashMainTimeline:FlashMainTimeline
---@field log_mc CombatLogFlashMC
---@field events table
---@field layout string
---@field isUIMoving boolean
---@field tooltip_array table
---@field onEventResize fun()
---@field onEventResolution fun(w:number, h:number)
---@field onEventUp fun(index:number)
---@field onEventInit fun()
---@field onEventDown fun(index:number)
---@field addFilter fun(index:number, tooltip:string, frame:number)
---@field addTab fun(tabTooltip:string)
---@field addTextToFilter fun(index:number, text:string)
---@field addTextToTab fun(index:number, text:string)
---@field clearAll fun()
---@field clearAllTexts fun()
---@field clearFilter fun(index:number)
---@field clearTab fun(index:number)
---@field reOpen fun()
---@field requestSize fun()
---@field selectFilter fun(index:number)
---@field setBGVisibility fun(b:boolean)
---@field setFilterSelection fun(index:number, b:boolean)
---@field setLockInput fun(b:boolean)
---@field setLogSize fun(b:number, param2:number)
---@field setLogVisible fun(b:boolean)
---@field setTooltip fun(index:number, tooltip:string)
---@field startsWith fun(str1:string, str2:string):boolean

---@class CombatLogFlashMC:FlashMovieClip
---@field bg_mc FlashMovieClip
---@field filterHolder_mc FlashMovieClip
---@field hide_mc FlashMovieClip
---@field lock_mc FlashMovieClip
---@field resize_mc FlashMovieClip
---@field visibility_mc FlashMovieClip
---@field filterList FlashHorizontalList
---@field filterAmount number
---@field filterDist number
---@field resized boolean
---@field textList FlashScrollList
---@field textOrder number
---@field currentText string
---@field isMouseOver boolean
---@field dragStartMP FlashPoint
---@field windowDragStarted boolean
---@field acceptInput boolean
---@field constrBoxX number
---@field constrBoxWidth number
---@field constrBoxHeight number
---@field constrBoxY number
---@field base FlashMovieClip
---@field fadeBG boolean
---@field lockInput boolean
---@field bgVisible boolean
---@field maxLinesCap number
---@field previousMax number
---@field frameW number
---@field sizeDispl number
---@field resizeDragging boolean
---@field addFilter fun(id:number, tooltip:string, frame:number)
---@field addTextToFilter fun(param1:number, param2:string)
---@field clearAll fun()
---@field clearAllTexts fun()
---@field clearFilter fun(param1:number)
---@field dragInv fun(param1:FlashMouseEvent)
---@field dragInvMove fun(param1:FlashMouseEvent)
---@field filterInput fun(param1:number, param2:boolean)
---@field getFilter fun(param1:number):CombatLogFlashFilter
---@field mouseLeave fun(param1:FlashEvent)
---@field onBgHide fun(param1:FlashMouseEvent)
---@field onBgMouseOut fun(param1:FlashMouseEvent)
---@field onBgMouseOver fun(param1:FlashMouseEvent)
---@field onBgShow fun(param1:FlashMouseEvent)
---@field onMoveResize fun(param1:FlashMouseEvent)
---@field onResizeOut fun(param1:FlashMouseEvent)
---@field onResizeOver fun(param1:FlashMouseEvent)
---@field onResizeStartDrag fun(param1:FlashMouseEvent)
---@field onResizeStopDrag fun(param1:FlashMouseEvent)
---@field onSBOut fun(param1:FlashMouseEvent)
---@field onSBOver fun(param1:FlashMouseEvent)
---@field refreshText fun()
---@field removeFilterEntriesFromList fun(param1:number)
---@field removeOldLines fun()
---@field resizing fun()
---@field selectFilter fun(param1:number)
---@field setBGVisibility fun(param1:boolean)
---@field setFilterSelection fun(param1:number, param2:boolean)
---@field setListWidths fun(param1:number)
---@field setLockInput fun(param1:boolean)
---@field setLogSize fun(param1:number, param2:number)
---@field setScrollWheelEnabled fun(param1:boolean)
---@field stopDragging fun()
---@field stopDragInv fun(param1:FlashMouseEvent)
---@field toggleFadeVisibility fun()
---@field toggleLock fun()

---@class FlashTweensyTimelineZero
---@field time number
---@field instance FlashObject
---@field key FlashObject
---@field ease function
---@field easeParams FlashArray<FlashObject>
---@field properties integer
---@field to FlashObject
---@field from FlashObject
---@field duration number
---@field delayStart number
---@field delayEnd number
---@field onUpdate function
---@field onUpdateParams FlashArray<FlashObject>
---@field onComplete function
---@field onCompleteParams FlashArray<FlashObject>
---@field update any

---@class CombatLogFlashFilter:FlashMovieClip
---@field id integer
---@field tooltip string
---@field bg_mc FlashMovieClip
---@field icon_mc FlashMovieClip
---@field fadeTime number
---@field selectedB boolean
---@field timeline FlashTweensyTimelineZero
---@field textContent string
---@field onDown fun(param1:FlashMouseEvent)
---@field onOut fun(param1:FlashMouseEvent)
---@field onOver fun(param1:FlashMouseEvent)

--#region Tooltips

---tt_groupHolder

---@class FlashTooltipElement:FlashMovieClip
---@field label_txt FlashTextField
---@field value_txt FlashTextField
---@field warning_txt FlashTextField

---@class FlashTooltipDescriptionElement:FlashMovieClip
---@field text_txt FlashTextField


---@class FlashTooltipGroupHolder:FlashMovieClip
---@field groupID number|nil
---@field container_mc FlashMovieClip
---@field icon_mc FlashMovieClip -- tt_groupIcon
---@field list FlashListDisplay
---@field base FlashMovieClip
---@field iconId integer
---@field textOffsetX number
---@field titleMC FlashMovieClip
---@field init function
---@field setupHeader function
---@field setTitle fun(text:string)
---@field addResist fun(labelText:string, iconFrame:number)
---@field addTag fun(labelText:string, valueText:string, warningText:string)
---@field addWandSkill fun(labelText:string, valueText:string, warningText?:string, iggyIconNum?:string)
---@field addRuneSlot fun(labelText:string, valueText:string, warningText?:string, runeEffectIconFrame?:number)
---@field addEl fun(labelText:string, valueText?:string, warningText?:string)
---@field addEl2 fun(labelText:string, valueText?:string, warningText?:string)
---@field addDescription fun(labelText:string)
---@field addWhiteSpace fun(index?:number, length?:number, leadingHeight?:number)
---@field addRequirement fun(labelText:string, valueText?:string, textColor?:integer)
---@field addWarning fun(labelText:string)
---@field addElNoColour fun(labelText:string, valueText?:string)
---@field setMCColour fun(mc:FlashMovieClip, color:integer)
---@field clearMC function

---@class FlashLSTooltipClass
---@field tooltipW number
---@field tooltipH number
---@field scaleH boolean
---@field maxH number
---@field tooltipPaddingL number
---@field tooltipPaddingR number
---@field tooltipPaddingB number
---@field SepSpacing number
---@field fixedTopSpacing integer
---@field fixedFooterSpacing integer
---@field hasSubSections boolean
---@field m_Leading number
---@field footerSpace number
---@field list FlashScrollList
---@field buttonHints FlashListDisplay
---@field equipHeader FlashMovieClip
---@field isItem boolean
---@field isIdentified boolean
---@field AbilityId number
---@field TalentId number
---@field groupLabels table
---@field groupColours table
---@field groupValueColours table
---@field unidentifiedMC FlashMovieClip
---@field forceHideFooter boolean
---@field btnHintHOffset number
---@field isEquipped boolean
---@field footer_mc FlashMovieClip
---@field container_mc FlashMovieClip
---@field middleBg_mc FlashMovieClip
---@field header_mc FlashMovieClip
---@field codeEnum FlashMovieClip -- Object
---@field grpsEnum FlashMovieClip -- Object
---@field width number
---@field height number
---@field setBGVisible fun(b:boolean)
---@field setGroupLabel fun(groupID:number, labelText:string)
---@field getHeight fun():number
---@field hideFooter function
---@field addButtonHint fun(id:number, hintText:string)
---@field clearButtonHints function
---@field setCompareHintVisible fun(b:boolean)
---@field applyLeading fun(mc:FlashMovieClip, amount?:number)
---@field roundToLeading fun(yPos:number, amount?:number):number
---@field scrollDown function
---@field scrollUp function
---@field stopScrolling function
---@field repositionElements function
---@field clear function
---@field clearContent function
---@field setupTooltip fun(arr:table, leading?:number)

---@class FlashTooltipFormattedMC
---@field tooltip_mc FlashLSTooltipClass
---@field resetBG function
---@field onRemove fun(e:FlashEvent)

---@class FlashStatusTooltipMC
---@field bg_mc FlashMovieClip
---@field text_txt FlashTextField
---@field setText fun(text:string)

---@class FlashItemCompareTooltip
---@field offhand_mc FlashMovieClip
---@field tooltip_mc FlashLSTooltipClass
---@field onRemove fun(e:FlashEvent)

---@class FlashTooltipMC
---@field bg_mc FlashMovieClip
---@field newBG_mc FlashMovieClip
---@field text_txt FlashTextField
---@field setText fun(text:string, bgType?:integer)

---@class FlashTooltipMainTimeline
---@field tooltip_mc FlashMovieClip -- Symbol 66, does not have an AS class
---@field events FlashArray
---@field layout string
---@field cachedStickToMouse number
---@field ComparePaneOffset number
---@field ComparePaneOffset2 number
---@field ComparePaneOffset3 number
---@field frame_width number
---@field frame_height number
---@field tf nil|FlashTooltipFormattedMC|FlashTooltipMC
---@field ctf nil|FlashItemCompareTooltip compareTooltip or offhandTooltip
---@field ohctf nil|FlashItemCompareTooltip offhandTooltip
---@field offsetX number
---@field offsetY number
---@field compareShowTimer FlashTimer -- Timer
---@field compareMode boolean
---@field tooltipModeTimer FlashTimer -- Timer
---@field tooltip_array FlashArray
---@field tooltipCompare_array FlashArray
---@field tooltipOffHand_array FlashArray
---@field formatTooltip FlashTooltipFormattedMC -- tooltipFormattedMC
---@field compareTooltip FlashItemCompareTooltip -- ItemCompareTooltip
---@field offhandTooltip FlashItemCompareTooltip -- ItemCompareTooltip
---@field defaultTooltip FlashTooltipMC -- tooltipMC
---@field statusTooltip FlashStatusTooltipMC -- statusTooltipMC
---@field NormalTooltip boolean
---@field isStatusTT boolean
---@field tooltipAlignmentLeft boolean
---@field setGroupLabel fun(groupID:number, labelText:string)
---@field setWindow fun(resWidth:number, resHeight:number)
---@field onEventInit function
---@field onEventResize function
---@field strReplace fun(str:string, delimiter:string, joinStr:string):string
---@field traceArray fun(arr:FlashArray)
---@field addFormattedTooltip fun(xPos?:number, yPos?:number, deferShow?:boolean)
---@field addStatusTooltip fun(xPos?:number, yPos?:number)
---@field addTooltip fun(text:string, widthOverride?:number, heightOverride?:number, allowDelay?:boolean, stickToMouse?:number, bgType?:integer)
---@field swapCompare function
---@field showFormattedTooltipAfterPos fun(isComparing:boolean)
---@field setCompare fun(b:boolean)
---@field addCompareTooltip fun(arr:FlashArray, unusedNum1?:number, unusedNum2?:number)
---@field addCompareOffhandTooltip fun(arr:FlashArray, unusedNum1?:number, unusedNum2?:number)
---@field INTshowTooltip function
---@field onShowCompareTooltip fun(e:FlashTimerEvent)
---@field startModeTimer function
---@field resetTooltipMode fun(e:FlashTimerEvent)
---@field onMove fun(e:FlashMouseEvent)
---@field INTRemoveTooltip function
---@field removeTooltip function
---@field fadeOutTooltip fun(unusedNum:number, fadeDuration:number)
---@field checkTooltipBoundaries fun(w:number, h:number, unused1:number, unused2:number)
---@field getTooltipHeight fun():number
---@field getTooltipWidth fun():number

--#endregion