Ext.Require("Shared/Classes/TranslatedString.lua")
Ext.Require("Shared/Classes/MessageData.lua")
Ext.Require("Shared/Classes/ClientData.lua")
Ext.Require("Shared/Classes/DeltaModGroup.lua")
Ext.Require("Shared/Classes/ModSettingsClasses.lua")