Ext.Require("Shared/Classes/LeaderLibGameSettings.lua")
Ext.Require("Shared/Classes/HitData.lua")
Ext.Require("Shared/Classes/MessageData.lua")
Ext.Require("Shared/Classes/SkillEventData.lua")
Ext.Require("Shared/Classes/TranslatedString.lua")