Ext.Require("Shared/_InitShared.lua")
Ext.Require("Shared/Helpers/ExtenderHelpers.lua")
Ext.Require("Shared/Helpers/SharedGameHelpers.lua")
Ext.Require("Shared/Helpers/StringHelpers.lua")
Ext.Require("Shared/Common.lua")
Ext.Require("Shared/Classes/_Init.lua")
Ext.Require("Shared/LeaderLibDefaultGlobalSettings.lua")
Ext.Require("Shared/Data/Init.lua")
Ext.Require("Shared/Main.lua")
Ext.Require("Shared/SharedDebug.lua")
Ext.Require("Shared/StatOverrides.lua")
Ext.Require("Shared/FeaturesHandler.lua")
Ext.Require("Shared/WingsWorkaround.lua")
-- if Ext.IsDeveloperMode() then
-- 	Ext.Require("Shared/Debug/GameMathTracing.lua")
-- end